name: Ansible
on: workflow_dispatch

jobs:
  Deploy:
    runs-on: ubuntu-24-04
    steps:
      - name: Install Ansible
        run: |
          python -m pip install ansible
          ansible --version
